version: '3'

services:
  alis:
    image: alis
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./Shared:/app/Shared
    networks:
      - backend

  


networks:
  backend:


