version: '3'

services:
  
  alis:
    image: alis
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_HOME=/usr/local/cuda
    volumes:
      - ./Shared:/app/Shared
    networks:
      - backend

  stylegan2:
    image: stylegan2
    ports:
      - 5001:5001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_HOME=/usr/local/cuda
    volumes:
      - ./Shared:/app/Shared
    networks:
      - backend
  
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend  

  worker:
    image: worker
    networks:
      - backend
    depends_on:
      - redis
      - alis
      - stylegan2

networks:
  backend:


