"""empty message

Revision ID: 2768f5be1f79
Revises: c988b2dd1e15
Create Date: 2023-05-22 22:20:12.691244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2768f5be1f79'
down_revision = 'c988b2dd1e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.drop_column('email')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
