"""empty message

Revision ID: 84490b1a769b
Revises: 12704e8e48a9
Create Date: 2023-07-15 18:23:16.079593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84490b1a769b'
down_revision = '12704e8e48a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_process', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('status_process')

    # ### end Alembic commands ###
